server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://635908:eyJrIjoiMTM4Y2JiMjg1Y2QxY2ZkYmM4ZDcxOTQwMzgzODU4OTk1YWQwMjlmMCIsIm4iOiJzdm5fcm5vIiwiaWQiOjg5MTM0OH0=@logs-prod-006.grafana.net/loki/api/v1/push 

scrape_configs:
- job_name: user_service
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
  pipeline_stages:
  - json: 
      expressions:
        level: level
        message: message
  - labels:
      level:
  - output:
      source: message
  static_configs:
  - targets:
      - localhost
    labels:
      job: user_service
      __path__: /var/log/*log
