server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
- job_name: user_service
  static_configs:
  - targets:
      - localhost
    labels:
      job: user_service
      __path__: /shared-volume/var/log/combined.log
